version: "3.7"

services:
  dockerbot:
    image: rkramesh/dockerbot:m3u
      #    image: techblog/dockerbot
    container_name: dockerbot1
    network_mode: host
    cap_add:
       - NET_ADMIN
    privileged: true
    restart: always
    environment:
      - API_KEY=${INFO_BOT_TOKEN}
      - ALLOWED_IDS=${CHAT_ID}
      - TELEGRAM_API_TOKEN=${INFO_BOT_TOKEN} 
      - TELEGRAM_GROUP_ID=${CHAT_ID}
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /etc/hostname:/etc/hostname:ro
       - '/etc/localtime:/etc/localtime:ro'
       - '/etc/timezone:/etc/timezone:ro'
       - /proc/sysrq-trigger:/sysrq
       - /media:/media
 
